// Auto-generated by @electron-ipc-bridge/vite-plugin
// Do not edit manually

import type { IpcApi } from "../../../frontend/src/ipc.types";

declare global {
  interface Window {
    ipc: IpcApi;
  }
}

export {};
