export const SYSTEM_CHANNELS = {
  GET_LOCALE: "GET_LOCALE",
  RESTART_APP: "RESTART_APP",
  RESTART_DEVICE: "RESTART_DEVICE",
  SHUTDOWN_DEVICE: "SHUTDOWN_DEVICE",
  SLEEP_DEVICE: "SLEEP_DEVICE",
} as const;
