export const GAME_CACHE_REFERENCE_KINDS = [
  "ageRating",
  "ageRatingCategory",
  "ageRatingContentDescription",
  "ageRatingOrganisation",
  "alternativeName",
  "artwork",
  "bundleGame",
  "collection",
  "company",
  "cover",
  "externalGame",
  "externalGameSource",
  "franchise",
  "gameEngine",
  "gameMode",
  "gameReleaseFormat",
  "gameStatus",
  "gameType",
  "gameVideo",
  "genre",
  "involvedCompany",
  "keyword",
  "language",
  "languageSupport",
  "languageSupportType",
  "multiplayerMode",
  "parentGame",
  "platform",
  "playerPerspective",
  "screenshot",
  "similarGame",
  "theme",
  "versionParent",
  "website",
  "websiteType",
] as const;

export type GameCacheReferenceKind = (typeof GAME_CACHE_REFERENCE_KINDS)[number];

export const GAME_RESOURCE_DEPENDENT_REFERENCE_KINDS = [
  "bundleGame",
  "parentGame",
  "similarGame",
  "versionParent",
] as const satisfies readonly GameCacheReferenceKind[];
