export const SYSTEM_CHANNELS = {
  GET_LOCALE: "GET_LOCALE",
  GET_OS: "GET_OS",
  RESTART_APP: "RESTART_APP",
  RESTART_DEVICE: "RESTART_DEVICE",
  SHUTDOWN_DEVICE: "SHUTDOWN_DEVICE",
  SLEEP_DEVICE: "SLEEP_DEVICE",
} as const;

export const WINDOW_CHANNELS = {
  CLOSE: "WINDOW_CLOSE",
  MAXIMIZE: "WINDOW_MAXIMIZE",
  MINIMIZE: "WINDOW_MINIMIZE",
} as const;

export const COLLECTION_CHANNELS = {
  CREATE: "CREATE_COLLECTION",
  DELETE: "DELETE_COLLECTION",
  GET_ALL: "GET_COLLECTIONS",
  GET_GAMES: "GET_COLLECTION_GAMES",
  UPDATE: "UPDATE_COLLECTION",
} as const;

export const GAME_CHANNELS = {
  GET_BY_ID: "GET_GAME_BY_ID",
  GET_FILTERED: "GET_FILTERED_GAMES",
  GET_FILTERS: "GET_GAME_FILTERS",
  GET_LAST_SYNCED: "GET_GAMES_LAST_SYNCED_AT",
  GET_LIST: "GET_GAMES_LIST",
  GET_NEW: "GET_NEW_GAMES",
  GET_PROTONDB_TIER: "GET_PROTONDB_TIER",
  INSTALL: "INSTALL_GAME",
  LAUNCH: "LAUNCH_GAME",
  REMOVE: "REMOVE_GAME",
  SYNC: "SYNC_GAMES",
  TOGGLE_FAVOURITE: "TOGGLE_FAVOURITE_GAME",
  UNINSTALL: "UNINSTALL_GAME",
} as const;

export const QUICK_ACCESS_CHANNELS = {
  GET_GAMES: "GET_QUICK_ACCESS_GAMES",
  TOGGLE_GAME: "TOGGLE_QUICK_ACCESS_GAME",
} as const;

export const INTEGRATION_CHANNELS = {
  AUTHENTICATE: "AUTHENTICATE_INTEGRATION",
  EPIC_GAMES_RESULT: "EPIC_GAMES_INTEGRATION_RESULT",
  TEST_STEAM: "TEST_STEAM_INTEGRATION",
} as const;

export const SECURITY_CHANNELS = {
  DECRYPT: "DECRYPT",
  ENCRYPT: "ENCRYPT",
} as const;

export const EVENT_CHANNELS = {
  COLLECTIONS_UPDATED: "EVENT_COLLECTIONS_LIST_UPDATED",
  GAMES_LIST_UPDATED: "EVENT_GAMES_LIST_UPDATED",
  GAME_SYNC_STATUS: "EVENT_GAME_SYNC_STATUS",
} as const;
