export const GET_LOCALE = "GET_LOCALE";
export const GET_OS = "GET_OS";

export const RESTART_APP = "RESTART_APP";
export const SLEEP_DEVICE = "SLEEP_DEVICE";
export const RESTART_DEVICE = "RESTART_DEVICE";
export const SHUTDOWN_DEVICE = "SHUTDOWN_DEVICE";

export const CREATE_COLLECTION = "CREATE_COLLECTION";
export const GET_COLLECTIONS = "GET_COLLECTIONS";
export const UPDATE_COLLECTION = "UPDATE_COLLECTION";
export const DELETE_COLLECTION = "DELETE_COLLECTION";

export const CLEAR_SYNC_QUEUE = "CLEAR_SYNC_QUEUE";
export const SYNC_GAMES = "SYNC_GAMES";
export const REMOVE_GAME = "REMOVE_GAME";
export const GET_FILTERED_GAMES = "GET_FILTERED_GAMES";
export const GET_GAME_FILTERS = "GET_GAME_FILTERS";
export const GET_GAME_BY_ID = "GET_GAME_BY_ID";
export const GET_GAMES_LAST_SYNCED_AT = "GET_GAMES_LAST_SYNCED_AT";
export const GET_PROTONDB_TIER = "GET_PROTONDB_TIER";
export const AUTHENTICATE_INTEGRATION = "AUTHENTICATE_INTEGRATION";

export const EVENT_SYNC_QUEUE_CLEARED = "EVENT_SYNC_QUEUE_CLEARED";
export const EVENT_GAMES_LIST_UPDATED = "EVENT_GAMES_LIST_UPDATED";
export const EVENT_METADATA_SYNC_INSERTED = "EVENT_METADATA_SYNC_INSERTED";
export const EVENT_METADATA_SYNC_SKIPPED = "EVENT_METADATA_SYNC_SKIPPED";
export const EVENT_METADATA_SYNC_PROCESSED = "EVENT_METADATA_SYNC_PROCESSED";
export const EVENT_METADATA_SYNC_COMPLETE = "EVENT_METADATA_SYNC_COMPLETE";
export const EVENT_COLLECTIONS_LIST_UPDATED = "EVENT_COLLECTIONS_LIST_UPDATED";

export const TEST_STEAM_INTEGRATION = "TEST_STEAM_INTEGRATION";

export const EPIC_GAMES_INTEGRATION_RESULT = "EPIC_GAMES_INTEGRATION_RESULT";

export const DECRYPT = "DECRYPT";
export const ENCRYPT = "ENCRYPT";

export const WINDOW_MINIMIZE = "WINDOW_MINIMIZE";
export const WINDOW_MAXIMIZE = "WINDOW_MAXIMIZE";
export const WINDOW_CLOSE = "WINDOW_CLOSE";

export const GET_GAMES_LIST = "GET_GAMES_LIST";
export const GET_NEW_GAMES = "GET_NEW_GAMES";

export const GET_COLLECTION_GAMES = "GET_COLLECTION_GAMES";
