export const EVENT_CHANNELS = {
  COLLECTIONS_UPDATED: "EVENT_COLLECTIONS_LIST_UPDATED",
  INTEGRATION_AUTH_RESULT: "EVENT_INTEGRATION_AUTH_RESULT",
  GAMES_LIST_UPDATED: "EVENT_GAMES_LIST_UPDATED",
  GAME_SYNC_STATUS: "EVENT_GAME_SYNC_STATUS",
} as const;
