export type {
  AgeRatingDto,
  AlternativeNameDto,
  CollectionDto,
  ExternalGameDto,
  GameDto,
  GameEngineDto,
  ImageDto,
  InvolvedCompanyDto,
  LanguageSupportDto,
  MultiplayerModeDto,
  ReferenceItemDto,
  RichReferenceItemDto,
  VideoDto,
  WebsiteDto,
} from "@stakload/game-cache-contracts";
