import { Module } from "@nestjs/common";
import { TypeOrmModule } from "@nestjs/typeorm";

import {
  ArtworkEntity,
  CollectionEntity,
  CompanyEntity,
  CompanyLogoEntity,
  CompanyStatusEntity,
  CoverEntity,
  ExternalGameEntity,
  ExternalGameSourceEntity,
  FranchiseEntity,
  GameCollectionEntity,
  GameEntity,
  GameFranchiseEntity,
  GameGenreEntity,
  GameKeywordEntity,
  GameModeEntity,
  GameModeLookupEntity,
  GamePlatformEntity,
  GamePlayerPerspectiveEntity,
  GameThemeEntity,
  GenreEntity,
  InvolvedCompanyEntity,
  KeywordEntity,
  PlatformEntity,
  PlatformFamilyEntity,
  PlatformLogoEntity,
  PlatformTypeEntity,
  PlatformVersionEntity,
  PlayerPerspectiveEntity,
  ReleaseDateEntity,
  ReleaseDateRegionEntity,
  ReleaseDateStatusEntity,
  ScreenshotEntity,
  ThemeEntity,
  WebsiteEntity,
  WebsiteTypeEntity,
} from "./entities";

const entities = [
  ArtworkEntity,
  CollectionEntity,
  CompanyEntity,
  CompanyLogoEntity,
  CompanyStatusEntity,
  CoverEntity,
  ExternalGameEntity,
  ExternalGameSourceEntity,
  FranchiseEntity,
  GameCollectionEntity,
  GameEntity,
  GameFranchiseEntity,
  GameGenreEntity,
  GameKeywordEntity,
  GameModeEntity,
  GameModeLookupEntity,
  GamePlatformEntity,
  GamePlayerPerspectiveEntity,
  GameThemeEntity,
  GenreEntity,
  InvolvedCompanyEntity,
  KeywordEntity,
  PlatformEntity,
  PlatformFamilyEntity,
  PlatformLogoEntity,
  PlatformTypeEntity,
  PlatformVersionEntity,
  PlayerPerspectiveEntity,
  ReleaseDateEntity,
  ReleaseDateRegionEntity,
  ReleaseDateStatusEntity,
  ScreenshotEntity,
  ThemeEntity,
  WebsiteEntity,
  WebsiteTypeEntity,
];

@Module({
  exports: [TypeOrmModule],
  imports: [TypeOrmModule.forFeature(entities)],
})
export class DatabaseEntitiesModule {}
